<?php

function oc_template_overwrites_nemid_form_callback ($form, &$form_state) {
   $current_path = $_SESSION['current_path']  ;
   $response = array(
    '#type' => 'ajax',
    '#commands' => array(),
  );

  $form['nemid']['#markup'] = '<a href="/wayf/consume?destination=' . $current_path . '" >Login med NemID </a>'
      . '<div class="ding-wayf-create-user"><a class="create-user-link" href="/wayf/create-user/before-page">Opret bruger</a><br><br><a target="_blank" href="/side/opret-bruger-med-nemid">Se guide til oprettelse.</a></div>';
  $response['#commands'][] = ajax_command_ding_popup('oc_template_overwrites', t('Login via NemID'), $form['nemid']['#markup'], array('refresh' => FALSE));

  return $response;
}
/*
 * Hooks into select modules template registry entries and swaps out with 
 * a position inside this module instead of their original module/templates.
 * allowing us to overwrite the backend functionality without including
 * templates in the admin theme.
 *  
 */
function oc_template_overwrites_theme_registry_alter(&$theme_registry)
{
    if(isset($theme_registry["opening_hours_admin"]))
    {
        $OC_template_repo = drupal_get_path('module','oc_template_overwrites') . "/templates";
        $theme_registry["opening_hours_admin"]["path"] = $OC_template_repo;
    }
    if(isset($theme_registry["file_entity"]))
    {
        $OC_template_repo = "file_entity";
        $ModuleTemplatePath = drupal_get_path('module','oc_template_overwrites') . "/templates";
        $theme_registry["file_entity"]["template"] = $OC_template_repo;
        $theme_registry["file_entity"]["path"] =  $ModuleTemplatePath;	
    }
}
/**
 * Implements hook_permission().
 */
function oc_template_overwrites_permission() {
  return array(
    'administer oc_template_overwrites' => array(
      'title' => t('Administrer oc_template_overwrites'),
      'description' => t('Giver adgang til configuere oc tempate overwrites'),

    )
  );
}
/*
 * 
 */
function  oc_template_overwrites_menu() {
  $items = array();
  $items['admin/settings/oc_template_overwrites'] = array(
    'title' => 'OC Overwrites',
    'description' => 'Configuration af oc digitalpost modul',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oc_template_overwrites_admin'),
    'access arguments' => array('administer oc_template_overwrites'),
    'file' => 'oc_template_overwrites.admin.inc'
   );
  
  return $items;
}
/*
 * Hook places where we want to inject.
 */
function oc_template_overwrites_preprocess_html(&$page)
{
    //Add javascript if we are on frontpage.
    $Path = drupal_get_path('module', 'oc_template_overwrites') . '/js/ting_tablesorter_parsers.js';
    drupal_add_js($Path);
    if(drupal_is_front_page() && variable_get('Place2book_front_ticket_status', 0) == 1) //The setting has been enabled.
    {
        $Path = drupal_get_path('module', 'oc_template_overwrites') . "/js/p2b_frontpagestatus.js";
        drupal_add_js($Path);
    }
    if (arg(0) == 'node' && arg(1) == 'add' || arg(2) == 'edit') {
        $path = drupal_get_path('module', 'oc_template_overwrites');  
        drupal_add_js($path . '/js/oc_material_descriptions.js',array('weight' => 999));
    }
    $config = array(
            'nysfyn_link' => variable_get('nysfyn_home_page', ''),
            'is_active' => variable_get('nysfyn_badge_enabled', 0),
            'google_translate_enabled' => variable_get('google_translate_enabled', 0),
            'google_translate_languages' => variable_get('google_translate_languages', 'da,de,en,es,nl,no')
           );
          drupal_add_js(array('oc_template_overwrites' => $config), 'setting');
  
  if(drupal_is_front_page())
    {
    $meta_description = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(     
      'content' => variable_get('description_meta'),
      'name' =>  'description',
    )
  );
      drupal_add_html_head($meta_description, 'meta_description');  
    }        
 // Setup IE meta tag to force IE rendering mode
  $meta_ie_render_engine = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'content' =>  'IE=Edge',
      'http-equiv' => 'X-UA-Compatible',
    )
  );
  // Add header meta tag for IE to head
  drupal_add_html_head($meta_ie_render_engine, 'meta_ie_render_engine');
}
/*
 * Contains various form alterations.
 */
function oc_template_overwrites_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    //dpm($form['#validate']);
    $form['#validate'][] = 'oc_template_overwrites_validate_user_phone';

  }
  elseif($form_id == 'user_login_block')
  {
      //$form['#validate'][] = 'oc_template_validate_login_user_id_length';
  }
  elseif($form_id == 'ding_news_node_form')
  {
      $form['#validate'][] = 'oc_template_validate_material_description_list';
      $form['#attached']['css'] = array(
        drupal_get_path('module', 'oc_template_overwrites') . '/css/material_descriptions.css',
      );
      foreach($form['field_ding_news_material_descrip']['und'] as $index => $elem)
      {
          if(is_array($elem) && isset($elem['#field_name']) && 
                  $elem['#field_name'] == 'field_ding_news_material_descrip' 
                  && isset($elem['value']) && is_array($elem['value'])  )
          {
              if($form['field_ding_news_material_descrip']['und'][$index]['value']['#default_value'] == "")
              {
                  $form['field_ding_news_material_descrip']['und'][$index]['value']['#default_value'] = '.';
              }
          }
      }
  }
} 
/*
 * Make sure the material description lists does not grow indefinit.
 */
function oc_template_validate_material_description_list($form, &$form_state)
{
    $field_index = sizeof($form_state['values']['field_ding_news_material_descrip']['und']);
    if(isset($form_state['values']['field_ding_news_material_descrip']['und'][$field_index-2]['value']) &&
       $form_state['values']['field_ding_news_material_descrip']['und'][$field_index-2]['value'] == ".")
    {
        unset($form_state['values']['field_ding_news_material_descrip']['und'][$field_index-2]);
    }
}
/*
 * Validate the phone number used for SMS notifcations
 * Prevent phone number with area codes and enforce 8 char length.
 */
function oc_template_overwrites_validate_user_phone($form, &$form_state)
{
    $errors = array();
    $phone_number = $form_state['values']['profile_provider_alma']['field_alma_mobile_phone']['und']['0']['value'];
    if(!ctype_digit($phone_number))
    {
        array_push($errors,t('Phone number must be numeric'));
    }
    $phone_lenght = strlen($phone_number);
    if($phone_lenght != 8)
    {
        array_push($errors,t('Phone number must be excactly 8 chars'));
    }
    if ($errors) {
        form_set_error_multiple('profile_provider_alma][field_alma_mobile_phone', $errors);
    }
}
/*
 * Login: Validate that a user id can max be 10 chars long.
 */
function oc_template_validate_login_user_id_length($form, &$form_state)
{
    $user_id_length = strlen($form_state['values']['name']);
    if($user_id_length > 10)
    {
        form_set_error('name_length_validate',t('User ID can max be 10 chars long.'));
    }
}
/*
 * Fix Default value for material descriptions. 
 */
function oc_template_widget_form_alter(&$element, &$form_state, $context)
{
    if(true)
    {
        
    }
}
/*
 * Helper to set multiple errors for 1 field.
 * http://drupal.stackexchange.com/questions/8327/how-to-set-multiple-error-messages-with-form-set-error
 */
function form_set_error_multiple($name = NULL, $messages = '', $limit_validation_errors = NULL) {
  return form_set_error($name, implode('<br/>', $messages));
}
